### ISSUE TITLE
How to provide regulators as inputs

### ISSUE THREAD

**Issue by samuel-g-bates** [AtteAalto/BINGO#2]
You mention in the read me that genes only interesting as potential regulators can be provided as inputs to the method.

How is this done? is the information given to data.inputs?

Thanks for your help,
Sam

**Comment by AtteAalto** [comment]
Hello!

Yes, indeed, genes that are only interesting as regulators, can be given in `data.inputs`. For example, say there’s a system of 100 genes with data in a matrix Y, of which genes 10-20 and 60-90 are only included as inputs, this is done as follows:

```
data.ts = {[Y([1:9 21:59 91:100],:)};
data.input = {Y([10:20 60:90],:)};
```

The resulting confidence matrix will then have size 78x100. Note that the columns of the confidence matrix are organised so that columns 1-78 will correspond to genes 1-9, 21-59 and 91-100, and columns 79-100 will correspond to those genes given as inputs.

Note: I have recently introduced different ways to interpolate input data. So far, this property is only implemented in the git branch named `notMeasured`. When including some genes as inputs, I recommend using linear interpolation between measurement times. This is chosen with an additional field in the data-structure, namely,

`data.inputInterpolation = ‘linear';`

**Comment by samuel-g-bates** [comment]
Thanks for the reply! Are you no longer able to indicate perturbation if
genes are given as inputs?

Thanks again,
Sam

**Comment by AtteAalto** [comment]
You can still include a perturbation as well, and concatenate it with the genes. If perturbations are in a matrix `U`, just put
`data.input = {[Y([10:20 60:90],:); U]};`
The different interpolation scheme doesn't really have an effect there, at least nothing significant.

**Comment by samuel-g-bates** [comment]
Thanks Dr.Aalto, I really appreciate your help.

Best,
Sam
